server:
  port: 9192

spring:
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE
  cloud:
    config:
      uri:
        - http://localhost:9196
logging:
  file:
    name: /home/tigelah/Área de Trabalho/logs/microservice.log
